name: .NET Build and Test
run-name: "Build and test on ${GITHUB_REF#refs/heads/}"
on:
  push:
    branches: [ main, development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.111
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  #release-linux:
  #  needs: build
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: dotnet publish
  #    run: dotnet publish
        
    
    
