name: "Create release on {{ github.ref }}"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.111
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        shell: bash
        run: |
          # Define some variables for things we need

          
          # Build everything
          dotnet publish src/Chirp.Razor/Chirp.Razor.csproj --runtime "linux-x64" -c Release -o "linux"
          dotnet publish src/Chirp.Razor/Chirp.Razor.csproj --runtime "win-x64" -c Release -o "windows"
          dotnet publish src/Chirp.Razor/Chirp.Razor.csproj --runtime "osx-x64" -c Release -o "osx"

          # Cleaning and zip'ing linux file
          cd linux
          #rm SimpleDB.pdb
          zip "Chirp-v${{ github.ref_name }}-linux-x64.zip" *
          mv "Chirp-v${{ github.ref_name }}-linux-x64.zip" ../
          cd ..

          # Cleaning and zip'ing windows file
          cd windows
          #rm SimpleDB.pdb
          zip "Chirp-v${{ github.ref_name }}-win-x64.zip" *
          mv "Chirp-v${{ github.ref_name }}-win-x64.zip" ../
          cd ..


          # Cleaning and zip'ing windows file
          cd osx
          #rm SimpleDB.pdb
          zip "Chirp-v${{ github.ref_name }}-osx-x64.zip" *
          mv "Chirp-v${{ github.ref_name }}-osx-x64.zip" ../
          cd ..
          
        
          # Delete output directory
          rm -r "linux"
          rm -r "windows"
          rm -r "osx"
          rm Chirp.sln
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Chirp*"
        env:
          GITHUB_TOKEN: ${{ secrets.action }}
