name: Publish
on:
  release:
    types: [published]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.111
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        shell: bash
        run: |
          # Define some variables for things we need

          
          # Build everything
          dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --runtime "linux-x64" -c Release -o "folders/linux"
          dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --runtime "win-x64" -c Release -o "folders/windows"
          dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --runtime "osx-x64" -c Release -o "folders/osx"


          # Pack files
          zip -r "Chirp-v${{ github.ref_name }}-linux-x64.zip" "folders/linux"
          zip -r "Chirp-v${{ github.ref_name }}-win-x64.zip" "folders/windows"
          zip -r "Chirp-v${{ github.ref_name }}-osx-x64.zip" "folders/osx"
          
        
          # Delete output directory
          rm -r "folders"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Chirp*"
        env:
          GITHUB_TOKEN: ${{ secrets.action }}
