name: Publish
on:
  release:
    types: [published]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.111
      - name: Build
        shell: bash
        run: |
          # Define some variables for things we need
          tag=$(git describe --tags --abbrev=0)
          echo "${{ github.ref }}" 

          
          # Build everything
          dotnet publish src/Chirp.CLI/App.csproj --framework netcoreapp3.1 --runtime "linux-x64" -c Release -o "folders/linux"
          dotnet publish src/Chirp.CLI/App.csproj --framework netcoreapp3.1 --runtime "windows-x64" -c Release -o "folders/windows"
          dotnet publish src/Chirp.CLI/App.csproj --framework netcoreapp3.1 --runtime "osx-x64" -c Release -o "folders/osx"


          # Pack files
          zip -r "Chirp-v0.0.0-linux-x64.zip" "folders/linux"
          zip -r "Chirp-v0.0.0-win-x64.zip" "folders/windows"
          zip -r "Chirp-v0.0.0-osx-x64.zip" "folders/osx"
          
        
          # Delete output directory
          rm -r "folders"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Chirp*"
        env:
          GITHUB_TOKEN: ${{ secrets.action }}
