name: Publish
on:
  release:
    types: [published]
jobs:
  release:
    name: Release
    runs-on: ubuntu latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.111
      - name: Build
        shell: bash
        run: |
          # Define some variables for things we need
          tag=$(git describe --tags --abbrev=0)
          release_name="App-$tag-${{ matrix.target }}"
        
          # Build everything
          dotnet publish src/Chirp.CLI/App.csproj --framework netcoreapp3.1 --runtime "linux-x64" -c Release -o "$release_name/linux"
          dotnet publish src/Chirp.CLI/App.csproj --framework netcoreapp3.1 --runtime "windows-x64" -c Release -o "$release_name/windows"
          dotnet publish src/Chirp.CLI/App.csproj --framework netcoreapp3.1 --runtime "osx-arm64" -c Release -o "$release_name/osx"


          # Pack files
          zip -r "Chirp-v${{release_name}}-linux-x64.zip" "$release_name/linux"
          zip -r "Chirp-v${{release_name}}-win-x64.zip" "$release_name/windows"
          zip -r "Chirp-v${{release_name}}-osx-x64.zip" "$release_name/osx"
        
          # Delete output directory
          rm -r "$release_name"
